### ISSUE TITLE
publish cad files in open format

### ISSUE THREAD

**Issue by Olm-e** [mathewlippincott/airpup-balloon#10]
hi, 
now the cad files are published in closed format (dxf -late version-  and fusion 360) impossible to use on a free operating system and difficult to work with or export to other software

stl are fine as well as svg and other open format

would it be possible that you export them and work with open format ? 
thanks a lot !
(planning to roll my own small scale version, actually wondering if not worth to redo it all instead of spending time on file export hunt... ;) )

**Comment by mathewlippincott** [comment]
Olm-e,
I do my best to use open source programs, and all the 2D CAD files are created in [QCAD](http://qcad.org/), which is F/OSS. I can do an SVG export as well, however I have to work in inches due to my factory relationship, and that makes SVGs a poor working format.

The STEP and IGES versions of the 3D files are the preferred cross-platform files. You should be able to open them in Blender or other 3D programs.

**Comment by mathewlippincott** [comment]
@Olm-e STLs have been available for all 3D printed components as well.
